### ISSUE TITLE
what is the model performace?

### ISSUE THREAD

**Issue by LinJM** [menglin0320/wap-on-tensor#1]

**Comment by menglin0320** [comment]
Well I guess it is about 0.4 exp rate, I didn't update the trained model nor training and validation data. This repo was only for development. I may better organize this repo after my internship finishes.

**Comment by LinJM** [comment]
I found the densenet model is not working properly.

**Comment by menglin0320** [comment]
I continued my work on another repo so don't try densenet. The model in Recognizer should work. If you don't care about spending time understanding my code, you can try to train the model.

**Comment by menglin0320** [comment]
The other repo is private.

**Comment by menglin0320** [comment]
There is also some bad naming I didn't change yet, like self.gru is actually lstm with zoneout.

**Comment by LinJM** [comment]
I test Reconizer's exp rate is 0.335 (330/985 ).

**Comment by menglin0320** [comment]
lol so bad. you can try not to use focal loss. I modified this model for an a little bit different task. This model is actually different from wap. I used zone out lstm instead of adaptive gaussian.
