### ISSUE TITLE
When training the model, we shouldn't always use label's last step value.

### ISSUE THREAD

**Issue by LinJM** [menglin0320/wap-on-tensor#2]
https://github.com/menglin0320/wap-on-tensor/blob/4fb2b953616c9438ffbc71313a0869e7ed5d6c9f/Recognizer.py#L273

In testing time, we don't know the actual label,  we just use argmax to get the last predict value, so in the training time we shouldn't always use label's last step value.

**Comment by menglin0320** [comment]
I called this method greedy method for obvious reason, I also implemented test.py which utilizes beam search.
I don't know if there's following research addressing your theory, the training method is called Connectionist Temporal	Classification. You can google it and search for papers.

**Comment by menglin0320** [comment]
Actually it's CTC loss, there may be some term abusing. I just saw it from other's repo

**Comment by menglin0320** [comment]
https://arxiv.org/abs/1612.00563 This paper used greedy evaluation on training, check this out.

**Comment by menglin0320** [comment]
I feel for this task you can find a lot of intuition or direction on papers for image captioning

**Comment by menglin0320** [comment]
After reviewing some paper on field of image captioning, I found that this decoding method is called **teacher forcing** and everyone is doing it for tasks like image captioning. Almost every recent paper on field of image captioning mentioned the "exposure bias" problem and stated that their method can mitigate this problem. I'll try to apply some recent research results on field of image captioning on this model. but generally speaking, any kind of regularization should mitigate this problem

**Comment by LinJM** [comment]
Thanks for your response. I know people usually use scheme sampling.
